### ISSUE TITLE
Use by other groups/mods

### ISSUE THREAD

**Issue by TedRinehart** [julianlam/nodebb-plugin-support-forum#1]
Following the groups overhaul in 0.6.1, are there any plans to expand this plugin so that a group other than Administrators can utilize a support forum, such as a group selected by the admin, perhaps enabling multiple support forums down the road?

At a glance, it seems as if category moderators could be used in place of Administrators through the use of [isModerator](https://github.com/NodeBB/NodeBB/wiki/Plugin-Hooks#filteruserismoderator). If I'm correct in this line of thought, then couldn't all users set as category moderators see and interact with user topics; Administrators who want to see these topics would also have to be set as moderators in accordance with the plugin alteration, correct?

**Comment by julianlam** [comment]
Yes, this is fairly easy to do. One thing to keep in mind is that this plugin overrides privileges for categories. You could set the category as readable for registered users, but this plugin will blindly overwrite it :)

**Comment by TedRinehart** [comment]
Excellent, glad to hear that is can be altered in such a fashion so simply.
