### ISSUE TITLE
remove "There is a new topic. Click here to reload" for support category

### ISSUE THREAD

**Issue by ShlomoCode** [julianlam/nodebb-plugin-support-forum#12]
![image](https://user-images.githubusercontent.com/78599753/168044023-d49c18c4-0114-4bf7-b87d-a3532b44e2e4.png)
Remove this alert for other topics in the support category - the user is asked to refresh, but then the new topic is hidden by the plugin... confusing situation :)
[In the next version of nodebb - 2.0.1, will be added the ability to control it.
](https://github.com/NodeBB/NodeBB/issues/10601#issuecomment-1123963899)(Writes here so that later I or anyone else will remember to do it...)

**Comment by ShlomoCode** [comment]
@julianlam Administrators do need to have an alert...
Even those who have opened the topic should have an alert for a new post

**Comment by julianlam** [comment]
Happy to review PRs for the additional functionality.

**Comment by ShlomoCode** [comment]
@julianlam I just checked out this new code. he does not work...
This hook does not seem to be called at all - I added `console.log(topic)`
And nothing was printed, neither in the browser's DevTools nor in the forum console on development status.
In addition the alert is not negligible, even when it comes to the support category

**Comment by ShlomoCode** [comment]
I now see that `config['support-forum']` contains nothing, and if so the condition never holds...
![image](https://user-images.githubusercontent.com/78599753/168922353-ca982f2f-b189-4094-9410-7926e01828ec.png)

**Comment by julianlam** [comment]
This requires NodeBB v2.0.1, which is as-yet unreleased. Perhaps that is why.

**Comment by ShlomoCode** [comment]
Ahh ... Okay, we'll wait and see :)
