### ISSUE TITLE
will this work for the latest version 0.9?

### ISSUE THREAD

**Issue by jeffbski** [julianlam/nodebb-plugin-support-forum#5]
I was looking for something like this, but it isn't clear whether it will work for the latest version 0.9.0?

plugin.json indicates ^0.6.0 support.

**Comment by julianlam** [comment]
Since the compatibility string is that old, it is likely the plugin is not *fully* compatible. 

I'd be open to updating it for compatibility if you require it, email us at sales@nodebb.org
