### ISSUE TITLE
Moving topic to another category has side-effects.

### ISSUE THREAD

**Issue by ELadner** [julianlam/nodebb-plugin-support-forum#7]
See this post for more details:  https://community.nodebb.org/topic/11804/moving-topic-from-one-category-to-another/9

Basically, moving a topic out of a support-forum category to another (more restrictive) category leaves behind a ghost topic that the creating user can still see (and see the first part of the latest comment on the right side).  No other users can see the topic once moved, and (as shown in the post) most of the CID/TID cross reference stuff in the database looks good.

Please consider fixing this!  I'm not opposed to offering a bounty.  This is important for my users.

**Comment by barisusakli** [comment]
I found the real issue in core, https://github.com/NodeBB/NodeBB/issues/6274. Thanks again for reporting @ELadner.

@julianlam can close this one.

**Comment by julianlam** [comment]
Awesome, thanks @barisusakli

**Comment by ELadner** [comment]
Thank you so much!
