### ISSUE TITLE
Bug - Direct access to other users' topics is not denied

### ISSUE THREAD

**Issue by ShlomoCode** [julianlam/nodebb-plugin-support-forum#8]
@julianlam  Peace,
Thanks for this great plugin!
There is a problem - although other users' topics do not appear in recent topics or in the category page, if a user gets a direct link to another user's topic he can access it! (Of course I marked "Non-admins see only their own topics listed" in ACP)
It also allows address guessing - if for example a user sees that after topic number 19 comes topic number 21, he will understand that topic number 20 is in the support category, will write in the browser: https://forum.com/topic/20 and can access and read!

**Comment by ShlomoCode** [comment]
@julianlam I discovered something else - alerts are sent on the topics in the category. Which means that other users receive an alert, click on it, and come to read another user's personal correspondence with the administration...
Which means that as long as this bug is not fixed, actually the plugin does not really work....

**Comment by julianlam** [comment]
Thank you for reporting, I will take a look when time permits.

**Comment by ShlomoCode** [comment]
@julianlam I'm trying to work on it to create a pull request ... :)
Can you tell me is this supposed to be treated, or should I add such a new feature?
I'm new to developing plugins for nodebb, so I suspect it's related ...
https://github.com/julianlam/nodebb-plugin-support-forum/blob/c156e950193f8dbd322a75b6e7041f41464d606d/library.js#L46-L58
I'm right?

**Comment by ShlomoCode** [comment]
Hi @julianlam , I wrote a fix for this bug ...
https://github.com/julianlam/nodebb-plugin-support-forum/pull/9
Can you merge please? Thanks.
